services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    command: flask --app main.py run --debug --host=0.0.0.0 --port=5000
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /app
          ignore:
            - __pycache__/

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 3000
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json
